Dataingestion service
CDCgov/NEDSS-Helm pull request #48
Opened 2023-08-02 03:36 UTC by ndduc01

Existing changes from previous sprint:
- EKS configuration for Data Ingestion

New changes from this sprint:
- Added pv, pvc, and added volume to deployment

2023-08-02 20:41 UTC, szamfir requested changes
It looks good, but I have a requested a couple of changes. For the time being please only create values-<env>.yaml files only where needed. I believe you should only need 1 at this time the one referred in my comments as values-dataingestion.yaml

2023-08-02 20:41 UTC, szamfir commented on charts/dataingestion-service/templates/NOTES.txt
This notes file references patient-search rather than dataingestion

2023-08-02 20:41 UTC, szamfir commented on charts/dataingestion-service/values-dev.yaml
this values-dev.yaml is intended to be used for the "dev/int" environment. If you want a values file for reference on you team please use a new file named something like values-dataingestion.yaml

2023-08-02 20:41 UTC, szamfir commented on charts/dataingestion-service/values-kafka-dev.yaml
What is this used for?

2023-08-02 20:46 UTC, ndduc01 commented on charts/dataingestion-service/values-kafka-dev.yaml
@bspuli

2023-08-03 04:11 UTC, ndduc01 commented on charts/dataingestion-service/templates/NOTES.txt
removed

2023-08-03 04:12 UTC, ndduc01 commented on charts/dataingestion-service/values-dev.yaml
renamed one and remove other value files

2023-09-05 14:27 UTC, bspuli commented on charts/dataingestion-service/values-kafka-dev.yaml
I will remove this

2023-09-05 14:34 UTC, szamfir approved these changes
It looks good. We will need to pivot to efs for deployment in int1. For the initial merge this is fine

2023-09-05 14:57 UTC, szamfir requested changes
Please rename *ebs* files to reflect the change to efs in the templates directory.

2023-09-05 14:57 UTC, szamfir commented on charts/dataingestion-service/templates/pv-ebs.yaml
Slightly misconfigured please check: https://github.com/CDCgov/NEDSS-Helm/blob/main/charts/elasticsearch-efs/templates/storageclass.yaml for reference.

2023-09-11 19:36 UTC, szamfir requested changes
Slight changes and please also change the following file names:
pv-ebs.yaml -> storageclass.yaml
pvc-ebs.yaml -> pvc-efs.yaml

2023-09-11 19:36 UTC, szamfir commented on charts/dataingestion-service/templates/pv-ebs.yaml
> +  name: efs-es
This name needs to be unique in the cluster, please change it to a unique name or make a reference here and anywhere this is called.

FYI there is a mismatch between this and the PVC which consumes this resource. To match simply change the name here to: {{ .Values.pvc.diPvClaim.storageClass | quote }}

2023-09-12 18:21 UTC, szamfir approved these changes
Looks good thank you!

2023-09-12 18:44 UTC, merged