fix ref to service
CDCgov/NEDSS-Helm pull request #74
Opened 2023-08-30 15:22 UTC by szamfir

2023-08-30 19:05 UTC, cmoss-enq requested changes
typo in name charts/modernization-api/templates/istio-ingress-virutalservice.yaml

2023-08-30 19:11 UTC, szamfir commented
> typo in name charts/modernization-api/templates/istio-ingress-virutalservice.yaml

Fixed along with a bonus fix for a resource name.

2023-08-31 12:34 UTC, pvijay-enquizit approved these changes

2023-09-05 14:15 UTC, cmoss-enq approved these changes
LGTM

2023-09-05 14:16 UTC, merged